# _config.yml

# Server Config

safe: true

source: ./src
destination: ./_site

timezone: Europe/London

future: false
lsi: false
pygments: false
markdown: rdiscount
rdiscount:
  extensions: [smart]

# Site Config

name: Birmingham Sports Awards 2014

url:
static: /static
media: /media
api: http://localhost/2014.birminghamsportsawards.co.uk/api

## Analytics

google_analytics_id: UA-37915390-4

## Meta

meta:
  author:
  description:
  keywords:
    - "birmingham sports awards"
    - "birmingham sport"
    - "sports awards"
    - "sports advertising"
    - "sports awards 2014"
    - "birmingham"
    - "birmingham sports awards winner"
    - "how to nominate"
    - "birmignham mail"
    - "birmingham post"
    - "sponsor awards"
    - "increase publicity"
